name: lab
channels:
  - plotly
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - autopep8
  - colorlog
  - coverage
  - flaky
  - libgcc
  - numpy
  - openpyxl
  - pandas
  - plotly-orca
  - psutil
  - pycodestyle
  - pydash=4.2.1
  - pytest-cov
  - pytest-timeout
  - pytest
  - python=3.7.3
  - pyyaml
  - regex
  - scipy
  - ujson
  - xlrd
  - pytorch=1.1.0
  - pip:
    - plotly
    - box2d-py==2.3.8
    - cloudpickle==0.5.2
    - colorlover==0.3.0
    - opencv-python
    - pyopengl==3.1.0
    - ray==0.7.0
    - redis==2.10.6
    - xvfbwrapper==0.2.9
    - gym==0.12.1
    - gym[atari]
    - gym[box2d]
    - gym[classic_control]
    - roboschool==1.0.46
    - atari-py
