version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: ff1651bfca53185e6d295b5989f89074b87fd7d68c6d1f938f19ea9186572a81

    working_directory: ~/SLM-Lab

    docker:
      - image: kengz/slm_lab:latest

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "environment.yml" }}

      - run:
          name: Install NodeJS dependencies
          command: |
            yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install Python dependencies with Conda
          command: |
            conda env update -f environment.yml
            pip uninstall -y tensorflow tensorboard
            pip uninstall -y box2d-kengz
            pip install box2d
            conda clean -y --all
      - save_cache:
          key: v1-dependencies-{{ checksum "environment.yml" }}
          paths:
            - ~/miniconda3
            - ~/.cache/pip

  test:
    environment:
      PY_ENV: test
      CC_TEST_REPORTER_ID: ff1651bfca53185e6d295b5989f89074b87fd7d68c6d1f938f19ea9186572a81

    working_directory: ~/SLM-Lab

    docker:
      - image: kengz/slm_lab:latest

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "environment.yml" }}

      - run:
          name: Run Python tests
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
            conda activate lab
            python setup.py test
            pytest --verbose --no-flaky-report test/spec/test_dist_spec.py
            cat coverage.xml
            ./cc-test-reporter after-build -d -p ~/SLM-Lab --exit-code $?
      - store_test_results:
          path: htmlcov

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
